plugins {
    id 'com.android.application'
}

android {
    namespace 'com.webtoapp.generated'
    compileSdk 34

    defaultConfig {
        applicationId "APP_PACKAGE_ID"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
